spring.application.name=orders-service
spring.security.user.name=sahan
spring.security.user.password=Password123

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
server.port=8083

# Optional: queue name
order.queue.name=orderQueue