<definitions targetNamespace="http://catalog.globalbooks.com/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://catalog.globalbooks.com/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <message name="GetPriceRequest"><part name="id" type="xsd:string"/></message>
    <message name="GetPriceResponse"><part name="price" type="xsd:double"/></message>
    <portType name="CatalogPortType"><operation name="getPrice"><input message="tns:GetPriceRequest"/><output message="tns:GetPriceResponse"/></operation></portType>
    <binding name="CatalogBinding" type="tns:CatalogPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="getPrice"><soap:operation soapAction=""/><input><soap:body use="literal"/></input><output><soap:body use="literal"/></output></operation>
    </binding>
    <service name="CatalogService"><port name="CatalogPort" binding="tns:CatalogBinding"><soap:address location="http://localhost:8080/CatalogService/catalog"/></port></service>
    <plnk:partnerLinkType name="CatalogLinkType"><plnk:role name="service" portType="tns:CatalogPortType"/></plnk:partnerLinkType>
</definitions>